declare const ERRORS: {}
declare const ERR$UNKNOWN: string
declare const ERR$ASSERT: string
declare const ERR$PARAM: string
declare const ERR$UNAUTHORIZED: string
declare const ERR$FORBIDDEN: string
declare const ERR$EMPTY: string
declare const ERR$SEARCH: string
declare const ERR$CONFIG: string
